### ISSUE TITLE
Layout is not set correctly on search

### ISSUE THREAD

**Issue by msbentley** [benji300/joplin-persistent-layout#7] opened 2021-02-04 09:59 UTC
I have tagged my notes, and when clicking from the notelist, this works extremely well. But when I search, the tag is not respected when the first hit in the filtered note-list is displayed. For example:

https://user-images.githubusercontent.com/1671065/106876391-ee7b6c80-66d7-11eb-9460-241eb0b584f1.mp4

## Versions
- plugin version: v1.1.1
- joplin version: 1.7.11
- operating system: linux
- OS version: ubuntu 20.04

**Comment by benji300** [comment] 2021-02-11 22:58
Thanks for your detailed error description. I can confirm the behavior. For example if you have a note selected with `layout:split` and then search for a note with `layout:rich` specified, the layout seems not to change. 

But technically it is changed... unfortunately it is changed twice in a row. So it seems it is not switched to the richtext layout. Also it seems only to be a problem if `layout:richtext` is involved. What I can see is, that the event `onNoteSelectionChange()` is triggered twice almost in parallel (I guess) when the search is executed. The following screenshot shows some debug messages I've added to the code. It is taken directly after the search was executed. There you can see that `toggleEditor` is triggered twice because previous check of global setting `codeView` results in true.

![image](https://user-images.githubusercontent.com/54955848/107708731-50ce0180-6cc4-11eb-821c-d94750ec5c6b.png)

I've created branch including the debug messages: https://github.com/benji300/joplin-persistent-layout/tree/search-issue-7

**Comment by msbentley** [comment] 2021-02-17 09:53
Thanks @benji300 - do you know if this has been flagged as an issue in the Joplin github?

**Comment by ken1kob** [comment] 2021-09-11 07:00
Thank you, @benji300,  for this very nice plugin.

I analyzed this issue, fixed it and sent a pull request.
The technical detail is very complicated and is described [this Joplin's issue](https://github.com/laurent22/joplin/issues/5447#issuecomment-917354916).

**Comment by benji300** [comment] 2021-09-26 20:57
Fixed with https://github.com/benji300/joplin-persistent-layout/releases/tag/v2.2.0

**Closed** 2021-09-26 20:57 UTC
Labels: bug
